### ISSUE TITLE
切换标题时内存增加很快

### ISSUE THREAD

**Issue by tony574273719** [iDvel/DDNews#1]

**Comment by iDvel** [comment]
`DDChannelCell.m`中`setUrlString`方法里的代码，除了这一行`_newsTVC.urlString = urlString;`，
剩下全放到`initWithFrame`里就解决内存飙升了。  
但是滑动时，cell都会先显示前一个的数据，然后再加载新数据，看起来有点丑。。。
而且如果网速不好的话，旧的不相关的数据会显示很久。
不知道怎么解决，就暂时没那么写 -_-...
